'use strict';

const DONATION_TYPES = {
  GET: 'DONATION_GET',
  GET_SUCCESS: 'DONATION_GET_SUCCESS',
  GET_ERROR: 'DONATION_GET_ERROR',
  DONATE: 'DONATION_DONATE',
  DONATE_SUCCESS: 'DONATION_SUCCESS',
  DONATE_ERROR: 'DONATION_ERROR',
};
